### ISSUE TITLE
magic-latex-buffer vs. x-symbol

### ISSUE THREAD

**Issue by wyousef** [zk-phi/magic-latex-buffer#21]
Thanks so much for your great package. I am trying installing x-symbols on Emacs 24.5.1; I am having a nightmare for several hours. It does not work.

So, is there a big difference between x-symbol and magic-latex-buffer?

Thanks so much

**Comment by zk-phi** [comment]
Sorry but I've never looked into `x-symbol` so much.

**Comment by zk-phi** [comment]
As I goolgled a bit just now, `x-symbol` seems not supporting block highlight/alignment but does support more languages.

**Comment by wyousef** [comment]
Thanks so much for your reply,

but regarding only LaTeX, can your package support the same exclusive
symbols by "X-Symbols"? I like your package much more since it is very
simple to use; I cannot even run X-Symbols so far. However, X-Symbols
seems to be so exclusive and supports almost all symbols, matrices, etc.

**Comment by zk-phi** [comment]
List of symbols can be easily updated and is not a fundamental difference.

**Comment by wyousef** [comment]
Are you planing to update a comprehensive list of symbols (including matrices)

**Comment by zk-phi** [comment]
you can find the list(s) [here](https://github.com/zk-phi/magic-latex-buffer/blob/master/magic-latex-buffer.el#L651) the code (I'm not sure what the word "matrices" here means).

**Comment by wyousef** [comment]
Could you guide me (in steps) what should I do to add a symbol? I tried
in the .el file but it seems that it loads the compiled file. How should
I add my new symbols in addition to yours

**Comment by zk-phi** [comment]
.el is not loaded if .elc exists.
you can remove .elc to force emacs to load .el, or you can also recompile the .el you edited to update .elc.

**Comment by wyousef** [comment]
Thanks so much for your support,

do you have any idea how can I produce the following:

1- \underset{a}{b}
2- both superscript and subscript for same symbol, e.g., \sum_a^b. Your
code does not put b as a superscript to \sum; rather it visualizes it as
a superscript to a.

Thanks so much, and sorry for many questions. But, I really love your
package and find it optimal solution for WYSIWYG for emacs.

**Comment by zk-phi** [comment]
The ideas are hard to realize I think.

The only way to align multiple chars vertically in a single line AFAIK
is, to compose multiple chars to form a single complex char like this
(try evaluating the followings in a Emacs buffer):

```` lisp
(insert (compose-chars ?d '(cr cl 0 0) ?e '(cr cl 0 0) ?f '(cc tc 0 0) ?=))
(insert "Σ"(compose-chars ?a '(bl tl 0 0) ?b))
````

But a copmosed char is treated as if it's a single char in Emacs, thus

* we no longer can highlight each single chars separately in a
  composed char

and

* we cannot move the cursor into the middle of a composed char (so we
  cannot edit each chars separately)

Since `magic-latex-buffer` 's aim isn't to transform Emacs into a
WYSIWYG editor but just to make it easier to read LaTeX documents with
pretty symbols (which I call `semi-WYSIWYG`), the current behavior is
okay I think.

For true rendering, `latex-math-preview` exists, which substitutes
maths with rendered images. Compared to this, the `magic-latex-buffer`
's advantage is that, maths are still just char sequences but not
images, and we can still utilize the text-based commands to edit
them. So, it's not good idea to (ab)use `compose-chars` IMO.

**Comment by zk-phi** [comment]
not interested anymore ? (closing ...)

**Comment by zk-phi** [comment]
closed
